### ISSUE TITLE
Vsync forced on with KMSDRM on Raspberry Pi 4

### ISSUE THREAD

**Issue by genpfault** [glmark2/glmark2#170] opened 2022-02-05 19:28 UTC
Looks like the DRM backend [is waiting for sync](https://github.com/glmark2/glmark2/blob/0858b450cd88c84a15b99dda9698d44e7f7e8c70/src/native-state-drm.cpp#L115-L116) even if `vblank_mode=0` is set at the Mesa level:

```
    int status = drmModePageFlip(fd_, encoder_->crtc_id, fb_->fb_id,
                                 DRM_MODE_PAGE_FLIP_EVENT, &waiting);
```

OR-ing in a `DRM_MODE_PAGE_FLIP_ASYNC` into the `flags` argument of `drmModePageFlip()` fixes it on my end:

```
diff --git a/src/native-state-drm.cpp b/src/native-state-drm.cpp
index d6bb743..93fd8c3 100644
--- a/src/native-state-drm.cpp
+++ b/src/native-state-drm.cpp
@@ -113,7 +113,7 @@ NativeStateDRM::flip()
     }
 
     int status = drmModePageFlip(fd_, encoder_->crtc_id, fb_->fb_id,
-                                 DRM_MODE_PAGE_FLIP_EVENT, &waiting);
+                                 DRM_MODE_PAGE_FLIP_EVENT | DRM_MODE_PAGE_FLIP_ASYNC, &waiting);
     if (status < 0) {
         Log::error("Failed to enqueue page flip: %d\n", status);
         return;
```

...though you'll probably want something a bit fancier like [SDL2's solution](https://github.com/libsdl-org/SDL/blob/release-2.0.20/src/video/kmsdrm/SDL_kmsdrmopengles.c#L157-L174) that tracks vsync enabled/disabled at the GL level & reacts appropriately.

**Comment by afrantzis** [comment] 2022-04-15 13:48
Hi! Thanks for the report, this is a duplicate of #122, let's continue the discussion there.

**Closed by afrantzis** 2022-04-15 13:49 UTC
